# Firefox ESR otherwise marks capture streams as immovable.
pulse.rules = [
  {
    matches = [
      { application.process.binary = "firefox-esr" }
    ]
    actions = {
      quirks = [ remove-capture-dont-move ]
    }
  }
]
